name: "Generate OG Image"
description: "Helps users generate a OG Image from frontmatter"
author: "Agney"
branding:
  icon: "share-2"
  color: "orange"
inputs:
  path:
    description: "Path to place generated assets"
    default: "demo/"
  commitMsg:
    description: "commit message to be shown when adding image"
    default: "just some wholesome content. yo all!"
  background:
    description: "background color for image"
    default: "#ffffff"
  fontColor:
    description: "font color for image"
    default: "#000000"
  componentUrl:
    description: "URL for web component"
    default: "https://unpkg.com/@agney/og-image-element@0.2.3"
  fontSize:
    description: "Font size for the root"
    default: "100%"
  width:
    description: "Width of the screen"
    default: "1200"
  height:
    description: "Height of the screen"
    default: "630"
  botComments:
    description: "Whether a comment with a preview image should be posted"
    default: "yes"
  ignorePatterns:
    description: "Comma-separated glob patterns for files to ignore"
    default: "/README.md"
runs:
  using: "docker"
  image: "Dockerfile"
