name: "Run tests"
on: [pull_request, push]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Setup Bun"
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: "Install dependencies"
        run: bun install --frozen-lockfile

      - name: "Type check"
        run: bun run typecheck

      - name: "Build release"
        run: bun run build-release

      - name: "Run tests"
        run: bun test

      - name: "check for uncommitted changes"
        # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
        run: |
          git diff --exit-code --stat -- . ':!node_modules' ':!bun.lockb' \
          || (echo "##[error] found changed files after build. please 'bun run build && bun run format'" \
                   "and check in all changes" \
              && exit 1)
